### ISSUE TITLE
newest version detected by Virus scan

### ISSUE THREAD

**Issue by hobolyra** [RussDev7/CoreKeepersWorkshop#10]
The other versions never had this issue, but the newest one is now seen as a threat by BitDefender, detecting "Trojan.GenericKD.69620455"

**Comment by RussDev7** [comment]
Files that are not commonly downloaded on the internet can cause this error, especially from one that edits a processes memory. So this in your case would be a false positive. You're welcome to either add an exception to your antivirus or build the project from the source code yourself.
