### ISSUE TITLE
Win Defender detects it as virus

### ISSUE THREAD

**Issue by Noutyr** [RussDev7/CoreKeepersWorkshop#13]
I downloaded the latest version (1.3.5.9) and I just _can't download_ it.
The navigator detects it as a virus and deletes it immediately, and Windows Defender detects it as **Trojan:Win32/DllInject**
I would recommend to check on it. Just in case.

**Comment by RussDev7** [comment]
This can happen to programs or applications that are not commonly downloaded from the internet. This mod works by editing the memory of the game and because of this, many antiviruses detect this and freak out. This is a false positive and you will have to add an exception through your antivirus.
