### ISSUE TITLE
Glurch position detection never works

### ISSUE THREAD

**Issue by Brycey92** [RussDev7/CoreKeepersWorkshop#14]
See #5. This is still an issue on the latest release, which was published after the March 2023 fix in the code.

**Comment by RussDev7** [comment]
Issue hopefully now fixed in 8a55d35fd41de27c28ab3d21c39b846d34d878af.

**Comment by Brycey92** [comment]
Sorry, no dice on that fix 😔

**Comment by bincbonc** [comment]
i also have the same issue, has this been resolved other than the fix from #5 ? i've tried that already and it doesn't work
