### ISSUE TITLE
Can't scan for teleport player

### ISSUE THREAD

**Issue by bincbonc** [RussDev7/CoreKeepersWorkshop#17]
I keep getting this error even if I'm already standing at the core's entrance. I have tried toggling the brute force setting on and off but it doesn't change anything.

![image](https://github.com/user-attachments/assets/58be8777-8c09-42c6-ac9f-f320aa0b4d55)

![image](https://github.com/user-attachments/assets/37cab50a-10a1-4c21-a807-ce277aed0c87)

![image](https://github.com/user-attachments/assets/e194e73b-2951-4ae1-81cb-56a5c544b8d4)

**Comment by RussDev7** [comment]
Thanks for the report. Looks like in the update / patch `0.7.5`, the world 0,0 base position was moved on X-Axis: 0.05 to the left.

Fixed in commit: 9905c82bf4c2e093ae3aadb01b3aae4e837414b7

**Comment by bincbonc** [comment]
thanks!
