### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by BourbonCrow** [RussDev7/CoreKeepersWorkshop#2]
missing decorations
[Gold-edged Table](https://corekeeper.wikizet.com/en/Gold-edged_Table)
[Big Gold-edged Table](https://corekeeper.wikizet.com/en/Big_Gold-edged_Table)

**Comment by RussDev7** [comment]
> missing decorations [Gold-edged Table](https://corekeeper.wikizet.com/en/Gold-edged_Table) [Big Gold-edged Table](https://corekeeper.wikizet.com/en/Big_Gold-edged_Table)

Thank you for the report. These will be added.

**Comment by RussDev7** [comment]
Assets added.
