### ISSUE TITLE
Missing Item Kelp Mantle

### ISSUE THREAD

**Issue by BourbonCrow** [RussDev7/CoreKeepersWorkshop#3]
8616 is the ID of the item https://corekeeper.wikizet.com/en/Kelp_Mantle
also letting you know i went though ALL equippable items to make sure no more was missing and this is the last missing equippable item

**Comment by RussDev7** [comment]
> 8616 is the ID of the item https://corekeeper.wikizet.com/en/Kelp_Mantle also letting you know i went though ALL equippable items to make sure no more was missing and this is the last missing equippable item

Thanks for the report, I have gone and added the missing asset.
