### ISSUE TITLE
<Players Tools - Speed> breaks the speed of vehicles. May block further use of the Workshop on this character.

### ISSUE THREAD

**Issue by XORandom** [RussDev7/CoreKeepersWorkshop#6]
**How to repeat the bug:** Change the speed value in the Player's Tools tab. Close the Workshop. (Optionally restart the game)
**Game Version:** The latest version is from March 8, 2023
**Modded or Vanilla:** Both

After closing CoreKeepersWorkshop, the values set by it are not reset. (This is not necessarily a bug, however I will mention it.)
As a result, in a normal game, you may have a character that moves at a crazy speed and you can't fix it, because to reactivate the Editor, you need to get into exactly the specified positions. 
I had to run a modified version and use the chat command mod to put the character in the right position. Because there is no way to do this in the vanilla version.

Also at the end of this video it can be seen that the speed change broke the speed of vehicles. They practically stopped moving at normal speed.

https://youtu.be/pq27lMzdhKs

**Comment by RussDev7** [comment]
All speed values changed via this mod will reset after you reload the world. This is a nice a simple solution encase you get "stuck" at a super slow walking speed. Thank you for taking the time to record a video and make a post on this.

**Comment by XORandom** [comment]
Thanks. I think that the reset should be done only for speed. The fact that the tools, for example, free crafting continue to work even after the closures Workshop, it's useful.
