### ISSUE TITLE
[bug] God Mode not enabling and Passive AI debuff

### ISSUE THREAD

**Issue by TheSilverWolfe** [RussDev7/CoreKeepersWorkshop#7]
After getting the newest CKW (1.3.5.1) I went to test out God Mode to which I was unfortunately slaughtered by an enemy. I tested this with Ground Magma Slime as well to which I also take damage. So then I decided to try Passive AI; it works but I'm noticing when toggled you automatically get a -25% movement debuff from a "mysterious aura". Thinking it was an error on my part probably with the initial player mapping I closed the program and game to restart and they persist with the new load.

**Can it be replicated**: Yes
**How**:
**-God Mode**; Enable God Mode toggle after getting the program started and situated, stand on Ground Magma Slime to gain Fire DoT, wait for first tick and see health deplete per tick of DoT. With enemy, after enabling God Mode stand next to enemy and get attacked.
**-Passive AI**; Enable Passive AI toggle after getting the program started and situated then move a few steps in any direction to gain movement debuff. Debuff disappears when toggling Passive AI off and is gained again when re-toggling and moving.
**Observations**: The only major observations I see is when toggling God Mode on the workshop there is nothing happening with the address bar above, unlike with options like Infinite Food or Passive AI which shows a progress bar when activating said toggles.

**Comment by RussDev7** [comment]
Thank you for the report, seems the update has moved some of these around. I will release a hotfix for this soon.

**Comment by RussDev7** [comment]
Update 1.3.5.2 closes this post.
